name: Deploy App

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          SECRET_DIR=${{ secrets.APP_DIR }}
          cd $SECRET_DIR
          LOG_FILE="deployment_$(date '+%Y-%m-%d_%H-%M-%S').log"
          { 
            git pull origin main &&
            php artisan migrate:fresh --force &&
            php artisan db:seed --force
          } > $LOG_FILE 2>&1 || {
            echo "An error occurred during deployment. See $LOG_FILE for details."
          }
